# -*- coding: utf-8 -*- --noconsole

import pyrebase
from getpass import getpass
import sys
from PySide2 import QtCore, QtGui, QtWidgets
from redacaoexpert import *
from requests import *
import logo_inicio_rc

firebaseConfig = {
    "apiKey": "AIzaSyB-Yeo4aQwwWlmP7JrsaKpYePoLRNlEsOo",
    "authDomain": "expertredacaooficial.firebaseapp.com",
    "databaseURL": "https://expertredacaooficial.firebaseio.com",
    "projectId": "expertredacaooficial",
    "storageBucket": "expertredacaooficial.appspot.com",
    "messagingSenderId": "783615378315",
    "appId": "1:783615378315:web:101be4ab6d8fdfc74aa58e",
    "measurementId": "G-BGBXNM2WLV"
}



firebase = pyrebase.initialize_app(firebaseConfig)
auth = firebase.auth()



class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setupUi(self)    

        def Cadastro():
                email = self.txt_cadastro_email.text()
                password = self.txt_cadastro_senha.text()
                if self.txt_cadastro_confirmsenha.text() ==  self.txt_cadastro_senha.text():
                    self.lbl_senhasdiferentes.setStyleSheet("color: rgb(255, 255, 255);")
                    user = auth.create_user_with_email_and_password(email, password)
                    self.Inicio_toolBox.hide()
                    self.frame_redacaoexpert.raise_

                else:
                    self.lbl_senhasdiferentes.setStyleSheet("color: rgb(255, 0, 0);")
        
        self.btn_cadastrar.clicked.connect(Cadastro)


        def Login():
            email = self.txt_login_email.text()
            password = self.txt_login_senha.text()
            user = auth.sign_in_with_email_and_password(email, password)
            user_id = auth.get_account_info(user['idToken'])
            print(user_id)
            if user is not False:
                print("Logado")

            else:
                print("Login não realizado")    
            
        self.btn_entrar.clicked.connect(Login)
        QtCore.QObject.connect(self.btn_entrar, QtCore.SIGNAL("clicked(bool)"), self.bwidget_1home.raise_)
        QtCore.QObject.connect(self.btn_entrar, QtCore.SIGNAL("clicked(bool)"), self.btn_trascinza0.raise_)
        QtCore.QObject.connect(self.btn_entrar, QtCore.SIGNAL("clicked(bool)"), self.widget_card_conceitosbasicos.raise_)
        QtCore.QObject.connect(self.btn_entrar, QtCore.SIGNAL("clicked(bool)"), self.btn_frente0.raise_)
        QtCore.QObject.connect(self.btn_entrar, QtCore.SIGNAL("clicked(bool)"), self.menu_home.raise_)
        QtCore.QObject.connect(self.btn_home1, QtCore.SIGNAL("clicked(bool)"), self.bwidget_1home.raise_)
        QtCore.QObject.connect(self.btn_home2, QtCore.SIGNAL("clicked(bool)"), self.bwidget_1home.raise_)
        QtCore.QObject.connect(self.btn_home1, QtCore.SIGNAL("clicked(bool)"), self.btn_home_clicado.raise_)
        QtCore.QObject.connect(self.btn_home2, QtCore.SIGNAL("clicked(bool)"), self.btn_home_clicado.raise_)
        QtCore.QObject.connect(self.btn_treinamento_4, QtCore.SIGNAL("clicked(bool)"), self.btn_treinamento_clicado.raise_)
        QtCore.QObject.connect(self.btn_treinamento_4, QtCore.SIGNAL("clicked(bool)"), self.bwidget_2treinamento.raise_)
        QtCore.QObject.connect(self.btn_treinamento_5, QtCore.SIGNAL("clicked(bool)"), self.bwidget_2treinamento.raise_)
        QtCore.QObject.connect(self.btn_treinamento_5, QtCore.SIGNAL("clicked(bool)"), self.btn_treinamento_clicado.raise_)
        QtCore.QObject.connect(self.btn_home, QtCore.SIGNAL("clicked(bool)"), self.btn_home_clicado.raise_)
        QtCore.QObject.connect(self.btn_treinamento_3semclicar, QtCore.SIGNAL("clicked(bool)"), self.btn_treinamento_clicado.raise_)
        QtCore.QObject.connect(self.btn_perfil_3, QtCore.SIGNAL("clicked(bool)"), self.bwidget_3perfil.raise_)
        QtCore.QObject.connect(self.btn_perfil_4semclicar, QtCore.SIGNAL("clicked(bool)"), self.bwidget_3perfil.raise_)
        QtCore.QObject.connect(self.btn_perfil_4semclicar, QtCore.SIGNAL("clicked(bool)"), self.btn_perfil_clicado.raise_)
        QtCore.QObject.connect(self.btn_perfil_3, QtCore.SIGNAL("clicked(bool)"), self.btn_perfil_clicado.raise_)
        QtCore.QObject.connect(self.btn_perfil_semclicar, QtCore.SIGNAL("clicked(bool)"), self.btn_perfil_clicado.raise_)
        QtCore.QObject.connect(self.btn_frente0, QtCore.SIGNAL("clicked(bool)"), self.widget_card_competencias.raise_)
        QtCore.QObject.connect(self.btn_frente0, QtCore.SIGNAL("clicked(bool)"), self.btn_frente1.raise_)
        QtCore.QObject.connect(self.btn_frente0, QtCore.SIGNAL("clicked(bool)"), self.btn_trasmarrom0.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom0, QtCore.SIGNAL("clicked(bool)"), self.widget_card_conceitosbasicos.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom0, QtCore.SIGNAL("clicked(bool)"), self.btn_frente0.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom0, QtCore.SIGNAL("clicked(bool)"), self.btn_trascinza0.raise_)
        QtCore.QObject.connect(self.btn_frente1, QtCore.SIGNAL("clicked(bool)"), self.widget_card_intro.raise_)
        QtCore.QObject.connect(self.btn_frente1, QtCore.SIGNAL("clicked(bool)"), self.btn_frente2.raise_)
        QtCore.QObject.connect(self.btn_frente1, QtCore.SIGNAL("clicked(bool)"), self.btn_trasmarrom1.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom1, QtCore.SIGNAL("clicked(bool)"), self.widget_card_competencias.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom1, QtCore.SIGNAL("clicked(bool)"), self.btn_trasmarrom0.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom1, QtCore.SIGNAL("clicked(bool)"), self.btn_frente1.raise_)
        QtCore.QObject.connect(self.btn_frente2, QtCore.SIGNAL("clicked(bool)"), self.widget_card_desenvolvimento.raise_)
        QtCore.QObject.connect(self.btn_frente2, QtCore.SIGNAL("clicked(bool)"), self.btn_frente3.raise_)
        QtCore.QObject.connect(self.btn_frente2, QtCore.SIGNAL("clicked(bool)"), self.btn_trasmarrom2.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom3, QtCore.SIGNAL("clicked(bool)"), self.widget_card_desenvolvimento.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom2, QtCore.SIGNAL("clicked(bool)"), self.btn_trasmarrom1.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom2, QtCore.SIGNAL("clicked(bool)"), self.btn_frente2.raise_)
        QtCore.QObject.connect(self.btn_frente3, QtCore.SIGNAL("clicked(bool)"), self.widget_card_conclusao.raise_)
        QtCore.QObject.connect(self.btn_frente3, QtCore.SIGNAL("clicked(bool)"), self.btn_trasmarrom3.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom2, QtCore.SIGNAL("clicked(bool)"), self.widget_card_intro.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom3, QtCore.SIGNAL("clicked(bool)"), self.btn_trasmarrom2.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom3, QtCore.SIGNAL("clicked(bool)"), self.btn_frente3.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom0, QtCore.SIGNAL("clicked(bool)"), self.btn_iniciar_conceitosbasicos.raise_)
        QtCore.QObject.connect(self.btn_frente0, QtCore.SIGNAL("clicked(bool)"), self.btn_iniciar2_competencias.raise_)
        QtCore.QObject.connect(self.btn_frente1, QtCore.SIGNAL("clicked(bool)"), self.btn_iniciar3_intro.raise_)
        QtCore.QObject.connect(self.btn_frente2, QtCore.SIGNAL("clicked(bool)"), self.btn_iniciar4_desenvol.raise_)
        QtCore.QObject.connect(self.btn_frente3, QtCore.SIGNAL("clicked(bool)"), self.btn_iniciar5_conclu.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom1, QtCore.SIGNAL("clicked(bool)"), self.btn_iniciar2_competencias.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom2, QtCore.SIGNAL("clicked(bool)"), self.btn_iniciar3_intro.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom3, QtCore.SIGNAL("clicked(bool)"), self.btn_iniciar4_desenvol.raise_)
        QtCore.QObject.connect(self.btn_frente3, QtCore.SIGNAL("clicked(bool)"), self.btn_frente4.raise_)
        QtCore.QObject.connect(self.btn_frente4, QtCore.SIGNAL("clicked(bool)"), self.widget_card_dicasextras.raise_)
        QtCore.QObject.connect(self.btn_frente4, QtCore.SIGNAL("clicked(bool)"), self.btn_frenteapagado.raise_)
        QtCore.QObject.connect(self.btn_frente4, QtCore.SIGNAL("clicked(bool)"), self.btn_trasmarrom4.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom4, QtCore.SIGNAL("clicked(bool)"), self.widget_card_conclusao.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom4, QtCore.SIGNAL("clicked(bool)"), self.btn_frente4.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom4, QtCore.SIGNAL("clicked(bool)"), self.btn_trasmarrom3.raise_)
        QtCore.QObject.connect(self.btn_frente4, QtCore.SIGNAL("clicked(bool)"), self.btn_iniciar6_dicasextras.raise_)
        QtCore.QObject.connect(self.btn_trasmarrom4, QtCore.SIGNAL("clicked(bool)"), self.btn_iniciar5_conclu.raise_)
        QtCore.QObject.connect(self.btn_iniciar_conceitosbasicos, QtCore.SIGNAL("clicked(bool)"), self.tela0_txt.raise_)
        QtCore.QObject.connect(self.btn_iniciar2_competencias, QtCore.SIGNAL("clicked(bool)"), self.tela1_competencias.raise_)
        QtCore.QObject.connect(self.btn_iniciar3_intro, QtCore.SIGNAL("clicked(bool)"), self.tela2_intro.raise_)
        QtCore.QObject.connect(self.btn_iniciar4_desenvol, QtCore.SIGNAL("clicked(bool)"), self.tela3_desenvolvimento.raise_)
        QtCore.QObject.connect(self.btn_iniciar5_conclu, QtCore.SIGNAL("clicked(bool)"), self.tela4_conclusao.raise_)
        QtCore.QObject.connect(self.btn_iniciar6_dicasextras, QtCore.SIGNAL("clicked(bool)"), self.tela5_dicasextras.raise_)
        QtCore.QObject.connect(self.tras1_telacompetencias, QtCore.SIGNAL("clicked(bool)"), self.bwidget_1home.raise_)
        QtCore.QObject.connect(self.tras2_telaintro, QtCore.SIGNAL("clicked(bool)"), self.bwidget_1home.raise_)
        QtCore.QObject.connect(self.tras3_teladesenvolvimento, QtCore.SIGNAL("clicked(bool)"), self.bwidget_1home.raise_)
        QtCore.QObject.connect(self.tras4_telaconclusao, QtCore.SIGNAL("clicked(bool)"), self.bwidget_1home.raise_)
        QtCore.QObject.connect(self.tras5_tela_dicasextras, QtCore.SIGNAL("clicked(bool)"), self.bwidget_1home.raise_)
        QtCore.QObject.connect(self.btn_proximotxt1, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt2.raise_)
        QtCore.QObject.connect(self.btn_proximotxt1, QtCore.SIGNAL("clicked(bool)"), self.txt1_2.raise_)
        QtCore.QObject.connect(self.btn_proximotxt2, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt3.raise_)
        QtCore.QObject.connect(self.btn_proximotxt2, QtCore.SIGNAL("clicked(bool)"), self.txt1_3.raise_)
        QtCore.QObject.connect(self.btn_proximotxt1, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt2.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt2, QtCore.SIGNAL("clicked(bool)"), self.txt1_1.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt2, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt1.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt2, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt1.raise_)
        QtCore.QObject.connect(self.btn_proximotxt2, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt3.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt3, QtCore.SIGNAL("clicked(bool)"), self.txt1_2.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt3, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt2.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt3, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt2.raise_)
        QtCore.QObject.connect(self.btn_iniciar_conceitosbasicos, QtCore.SIGNAL("clicked(bool)"), self.txt1_1.raise_)
        QtCore.QObject.connect(self.btn_iniciar_conceitosbasicos, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt1.raise_)
        QtCore.QObject.connect(self.btn_iniciar_conceitosbasicos, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt1.raise_)
        QtCore.QObject.connect(self.tras0_telatxt, QtCore.SIGNAL("clicked(bool)"), self.mensagemsair.raise_)
        QtCore.QObject.connect(self.a0btnsim1, QtCore.SIGNAL("clicked(bool)"), self.bwidget_1home.raise_)
        QtCore.QObject.connect(self.a0btnnao1, QtCore.SIGNAL("clicked(bool)"), self.mensagemsair.lower)
        QtCore.QObject.connect(self.btn_proximotxt3, QtCore.SIGNAL("clicked(bool)"), self.txt1_4.raise_)
        QtCore.QObject.connect(self.btn_proximotxt3, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt4.raise_)
        QtCore.QObject.connect(self.btn_proximotxt3, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt4.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt4, QtCore.SIGNAL("clicked(bool)"), self.txt1_3.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt4, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt3.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt4, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt3.raise_)
        QtCore.QObject.connect(self.btn_proximotxt4, QtCore.SIGNAL("clicked(bool)"), self.txt1_5.raise_)
        QtCore.QObject.connect(self.btn_proximotxt4, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt5.raise_)
        QtCore.QObject.connect(self.btn_proximotxt4, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt5.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt5, QtCore.SIGNAL("clicked(bool)"), self.txt1_4.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt5, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt4.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt5, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt4.raise_)
        QtCore.QObject.connect(self.btn_proximotxt5, QtCore.SIGNAL("clicked(bool)"), self.txt1_6.raise_)
        QtCore.QObject.connect(self.btn_proximotxt5, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt6.raise_)
        QtCore.QObject.connect(self.btn_proximotxt5, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt6.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt6, QtCore.SIGNAL("clicked(bool)"), self.txt1_5.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt6, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt5.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt6, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt5.raise_)
        QtCore.QObject.connect(self.btn_proximotxt1, QtCore.SIGNAL("clicked(bool)"), self.carregado2.raise_)
        QtCore.QObject.connect(self.btn_iniciar_conceitosbasicos, QtCore.SIGNAL("clicked(bool)"), self.carregado1.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt2, QtCore.SIGNAL("clicked(bool)"), self.carregado1.raise_)
        QtCore.QObject.connect(self.btn_proximotxt2, QtCore.SIGNAL("clicked(bool)"), self.carregado3.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt3, QtCore.SIGNAL("clicked(bool)"), self.carregado2.raise_)
        QtCore.QObject.connect(self.btn_proximotxt3, QtCore.SIGNAL("clicked(bool)"), self.carregado4.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt4, QtCore.SIGNAL("clicked(bool)"), self.carregado3.raise_)
        QtCore.QObject.connect(self.btn_proximotxt4, QtCore.SIGNAL("clicked(bool)"), self.carregado5.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt5, QtCore.SIGNAL("clicked(bool)"), self.carregado4.raise_)
        QtCore.QObject.connect(self.btn_proximotxt5, QtCore.SIGNAL("clicked(bool)"), self.carregado6.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt6, QtCore.SIGNAL("clicked(bool)"), self.carregado5.raise_)
        QtCore.QObject.connect(self.btn_proximotxt6, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt7.raise_)
        QtCore.QObject.connect(self.btn_proximotxt6, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt7.raise_)
        QtCore.QObject.connect(self.btn_proximotxt6, QtCore.SIGNAL("clicked(bool)"), self.carregado7.raise_)
        QtCore.QObject.connect(self.btn_proximotxt6, QtCore.SIGNAL("clicked(bool)"), self.txt1_7.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt7, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt6.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt7, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt6.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt7, QtCore.SIGNAL("clicked(bool)"), self.txt1_6.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt7, QtCore.SIGNAL("clicked(bool)"), self.carregado6.raise_)
        QtCore.QObject.connect(self.btn_proximotxt7, QtCore.SIGNAL("clicked(bool)"), self.txt1_8.raise_)
        QtCore.QObject.connect(self.btn_proximotxt7, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt8.raise_)
        QtCore.QObject.connect(self.btn_proximotxt7, QtCore.SIGNAL("clicked(bool)"), self.carregado8.raise_)
        QtCore.QObject.connect(self.btn_proximotxt7, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt8.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt8, QtCore.SIGNAL("clicked(bool)"), self.txt1_7.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt8, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt7.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt8, QtCore.SIGNAL("clicked(bool)"), self.carregado7.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt8, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt7.raise_)
        QtCore.QObject.connect(self.btn_proximotxt8, QtCore.SIGNAL("clicked(bool)"), self.txt1_9.raise_)
        QtCore.QObject.connect(self.btn_proximotxt8, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt9.raise_)
        QtCore.QObject.connect(self.btn_proximotxt8, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt9.raise_)
        QtCore.QObject.connect(self.btn_proximotxt8, QtCore.SIGNAL("clicked(bool)"), self.carregado9.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt9, QtCore.SIGNAL("clicked(bool)"), self.txt1_8.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt9, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt8.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt9, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt8.raise_)
        QtCore.QObject.connect(self.btn_anteriortxt9, QtCore.SIGNAL("clicked(bool)"), self.carregado8.raise_)
        QtCore.QObject.connect(self.btn_proximotxt9, QtCore.SIGNAL("clicked(bool)"), self.txt2_10.raise_)
        QtCore.QObject.connect(self.btn_proximotxt9, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxtz10.raise_)
        QtCore.QObject.connect(self.btn_proximotxt9, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxtz10.raise_)
        QtCore.QObject.connect(self.btn_proximotxt9, QtCore.SIGNAL("clicked(bool)"), self.carregadoz10.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz10, QtCore.SIGNAL("clicked(bool)"), self.txt1_9.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz10, QtCore.SIGNAL("clicked(bool)"), self.carregado9.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz10, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt9.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz10, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt9.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz10, QtCore.SIGNAL("clicked(bool)"), self.txt2_11.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz10, QtCore.SIGNAL("clicked(bool)"), self.carregadoz11.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz10, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxtz11.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz10, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxtz11.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz11, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxtz10.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz11, QtCore.SIGNAL("clicked(bool)"), self.carregadoz10.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz11, QtCore.SIGNAL("clicked(bool)"), self.txt2_10.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz11, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxtz10.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz11, QtCore.SIGNAL("clicked(bool)"), self.txt2_12.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz11, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxtz12.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz11, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxtz12.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz11, QtCore.SIGNAL("clicked(bool)"), self.carregadoz12.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz12, QtCore.SIGNAL("clicked(bool)"), self.txt2_11.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz12, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxtz11.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz12, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxtz11.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz12, QtCore.SIGNAL("clicked(bool)"), self.carregadoz11.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz12, QtCore.SIGNAL("clicked(bool)"), self.txt2_13.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz12, QtCore.SIGNAL("clicked(bool)"), self.carregadoz13.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz12, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxtz13.raise_)
        QtCore.QObject.connect(self.btn_proximotxtz12, QtCore.SIGNAL("clicked(bool)"), self.btn_responderquestionario1.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz13, QtCore.SIGNAL("clicked(bool)"), self.txt2_12.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz13, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxtz12.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz13, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxtz12.raise_)
        QtCore.QObject.connect(self.btn_anteriortxtz13, QtCore.SIGNAL("clicked(bool)"), self.carregadoz12.raise_)
        QtCore.QObject.connect(self.btn_responderquestionario1, QtCore.SIGNAL("clicked(bool)"), self.widget_questionario1.raise_)
        QtCore.QObject.connect(self.btn_responderquestionario1, QtCore.SIGNAL("clicked(bool)"), self.btn_revisarcardtxt.raise_)
        QtCore.QObject.connect(self.btn_responderquestionario1, QtCore.SIGNAL("clicked(bool)"), self.btn_enviarrespostaconceitos1.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio1, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio2.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio1, QtCore.SIGNAL("clicked(bool)"), self.widget_questionario2.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio1, QtCore.SIGNAL("clicked(bool)"), self.btn_questaoanterior1.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior1, QtCore.SIGNAL("clicked(bool)"), self.widget_questionario1.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior1, QtCore.SIGNAL("clicked(bool)"), self.btn_revisarcardtxt.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior1, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio1.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio2, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio3.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio2, QtCore.SIGNAL("clicked(bool)"), self.widget_questionario3.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio2, QtCore.SIGNAL("clicked(bool)"), self.btn_questaoanterior2.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior2, QtCore.SIGNAL("clicked(bool)"), self.widget_questionario2.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior2, QtCore.SIGNAL("clicked(bool)"), self.btn_questaoanterior1.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior2, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio2.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio3, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio4.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio3, QtCore.SIGNAL("clicked(bool)"), self.btn_questaoanterior3.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior3, QtCore.SIGNAL("clicked(bool)"), self.widget_questionario3.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior3, QtCore.SIGNAL("clicked(bool)"), self.btn_questaoanterior2.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior3, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio3.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio3, QtCore.SIGNAL("clicked(bool)"), self.widget_questionario4.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio4, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio5.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio4, QtCore.SIGNAL("clicked(bool)"), self.widget_questionario5.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio4, QtCore.SIGNAL("clicked(bool)"), self.btn_questaoanterior4.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior4, QtCore.SIGNAL("clicked(bool)"), self.widget_questionario4.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior4, QtCore.SIGNAL("clicked(bool)"), self.btn_questaoanterior3.raise_)
        QtCore.QObject.connect(self.btn_questaoanterior4, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio2.raise_)
        QtCore.QObject.connect(self.btn_revisarcardtxt, QtCore.SIGNAL("clicked(bool)"), self.tela0_txt.raise_)
        QtCore.QObject.connect(self.btn_revisarcardtxt, QtCore.SIGNAL("clicked(bool)"), self.txt1_1.raise_)
        QtCore.QObject.connect(self.btn_revisarcardtxt, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt1.raise_)
        QtCore.QObject.connect(self.btn_revisarcardtxt, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt1.raise_)
        QtCore.QObject.connect(self.btn_revisarcardtxt, QtCore.SIGNAL("clicked(bool)"), self.carregado1.raise_)
        QtCore.QObject.connect(self.btn_entrar, QtCore.SIGNAL("clicked(bool)"), self.bwidget_1home.raise_)
        self.btn_enviarrespostaconceitos1.clicked.connect(lambda: self.btn_clk(self.txt_question1certa.isChecked()))
        self.btn_enviarrespostaconceitos2.clicked.connect(lambda: self.btn_clk2(self.txt_question2certa.isChecked()))
        self.btn_enviarrespostaconceitos3.clicked.connect(lambda: self.btn_clk3(self.txt_question3certa.isChecked()))
        self.btn_enviarrespostaconceitos4.clicked.connect(lambda: self.btn_clk4(self.txt_question4certa.isChecked()))
        self.btn_enviarrespostaconceitos5.clicked.connect(lambda: self.btn_clk5(self.txtquestion5certa.isChecked()))
        QtCore.QObject.connect(self.btn_enviarrespostaconceitos1, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio1.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio1, QtCore.SIGNAL("clicked(bool)"), self.btn_enviarrespostaconceitos2.raise_)
        QtCore.QObject.connect(self.btn_enviarrespostaconceitos2, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio2.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio2, QtCore.SIGNAL("clicked(bool)"), self.btn_enviarrespostaconceitos3.raise_)
        QtCore.QObject.connect(self.btn_enviarrespostaconceitos3, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio3.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio3, QtCore.SIGNAL("clicked(bool)"), self.btn_enviarrespostaconceitos4.raise_)
        QtCore.QObject.connect(self.btn_enviarrespostaconceitos4, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio4.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio4, QtCore.SIGNAL("clicked(bool)"), self.btn_enviarrespostaconceitos5.raise_)
        QtCore.QObject.connect(self.btn_enviarrespostaconceitos5, QtCore.SIGNAL("clicked(bool)"), self.btn_proximoquestio5.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio5, QtCore.SIGNAL("clicked(bool)"), self.bwidget_1home.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio5, QtCore.SIGNAL("clicked(bool)"), self.widget_cartaconceitoscompleta.raise_)
        QtCore.QObject.connect(self.btn_proximoquestio5, QtCore.SIGNAL("clicked(bool)"), self.btn_iniciar_conceitosbasicos_2.raise_)
        QtCore.QObject.connect(self.btn_iniciar_conceitosbasicos_2, QtCore.SIGNAL("clicked(bool)"), self.tela0_txt.raise_)
        QtCore.QObject.connect(self.btn_iniciar_conceitosbasicos_2, QtCore.SIGNAL("clicked(bool)"), self.txt1_1.raise_)
        QtCore.QObject.connect(self.btn_iniciar_conceitosbasicos_2, QtCore.SIGNAL("clicked(bool)"), self.btn_anteriortxt1.raise_)
        QtCore.QObject.connect(self.btn_iniciar_conceitosbasicos_2, QtCore.SIGNAL("clicked(bool)"), self.btn_proximotxt1.raise_)
        QtCore.QObject.connect(self.btn_iniciar_conceitosbasicos_2, QtCore.SIGNAL("clicked(bool)"), self.carregado1.raise_)



        def btn_limparconceitos2():
            self.txt_question1certa.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question1errada2.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question1errada3.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question1errada4.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question1errada5.setStyleSheet("color: rgb(0, 0, 0);")

            self.txt_question2certa.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question2errada1.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question2errada2.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question2errada3.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question2errada4.setStyleSheet("color: rgb(0, 0, 0);")

            self.txt_question3certa.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question3errada1.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question3errada2.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question3errada3.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question3errada4.setStyleSheet("color: rgb(0, 0, 0);")

            self.txt_question4certa.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question4errada1.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question4errada2.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question4errada3.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question4errada4.setStyleSheet("color: rgb(0, 0, 0);")

            self.txtquestion5certa.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question5errada1.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question5errada2.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question5errada3.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question5errada4.setStyleSheet("color: rgb(0, 0, 0);")
    
        self.a0btnsim1.clicked.connect(btn_limparconceitos2)

        def btn_limparconceitos1():
            self.txt_question1certa.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question1errada2.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question1errada3.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question1errada4.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question1errada5.setStyleSheet("color: rgb(0, 0, 0);")

            self.txt_question2certa.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question2errada1.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question2errada2.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question2errada3.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question2errada4.setStyleSheet("color: rgb(0, 0, 0);")

            self.txt_question3certa.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question3errada1.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question3errada2.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question3errada3.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question3errada4.setStyleSheet("color: rgb(0, 0, 0);")

            self.txt_question4certa.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question4errada1.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question4errada2.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question4errada3.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question4errada4.setStyleSheet("color: rgb(0, 0, 0);")

            self.txtquestion5certa.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question5errada1.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question5errada2.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question5errada3.setStyleSheet("color: rgb(0, 0, 0);")
            self.txt_question5errada4.setStyleSheet("color: rgb(0, 0, 0);")
    
        self.btn_revisarcardtxt.clicked.connect(btn_limparconceitos1)
        
    def btn_clk2(self, chk):
        if chk:    
            self.txt_question2certa.setStyleSheet("color: rgb(0, 170, 0);")
            self.txt_question2errada1.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question2errada2.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question2errada3.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question2errada4.setStyleSheet("color: rgb(255, 0, 0);")
        else:
            self.txt_question2certa.setStyleSheet("color: rgb(0, 170, 0);")
            self.txt_question2errada1.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question2errada2.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question2errada3.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question2errada4.setStyleSheet("color: rgb(255, 0, 0);")

    def btn_clk3(self, chk):
        if chk:    
            self.txt_question3certa.setStyleSheet("color: rgb(0, 170, 0);")
            self.txt_question3errada1.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question3errada2.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question3errada3.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question3errada4.setStyleSheet("color: rgb(255, 0, 0);")
        else:
            self.txt_question3certa.setStyleSheet("color: rgb(0, 170, 0);")
            self.txt_question3errada1.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question3errada2.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question3errada3.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question3errada4.setStyleSheet("color: rgb(255, 0, 0);")

    def btn_clk4(self, chk):
        if chk:    
            self.txt_question4certa.setStyleSheet("color: rgb(0, 170, 0);")
            self.txt_question4errada1.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question4errada2.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question4errada3.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question4errada4.setStyleSheet("color: rgb(255, 0, 0);")
        else:
            self.txt_question4certa.setStyleSheet("color: rgb(0, 170, 0);")
            self.txt_question4errada1.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question4errada2.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question4errada3.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question4errada4.setStyleSheet("color: rgb(255, 0, 0);")

    def btn_clk5(self, chk):
        if chk:    
            self.txtquestion5certa.setStyleSheet("color: rgb(0, 170, 0);")
            self.txt_question5errada1.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question5errada2.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question5errada3.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question5errada4.setStyleSheet("color: rgb(255, 0, 0);")
        else:
            self.txtquestion5certa.setStyleSheet("color: rgb(0, 170, 0);")
            self.txt_question5errada1.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question5errada2.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question5errada3.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question5errada4.setStyleSheet("color: rgb(255, 0, 0);")

    def btn_clk(self, chk):
        if chk:    
            self.txt_question1certa.setStyleSheet("color: rgb(0, 170, 0);")
            self.txt_question1errada2.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question1errada3.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question1errada4.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question1errada5.setStyleSheet("color: rgb(255, 0, 0);")
        else:
            self.txt_question1certa.setStyleSheet("color: rgb(0, 170, 0);")
            self.txt_question1errada2.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question1errada3.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question1errada4.setStyleSheet("color: rgb(255, 0, 0);")
            self.txt_question1errada5.setStyleSheet("color: rgb(255, 0, 0);")
        

                    
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())



